### ISSUE TITLE
Problem with size of AAPT

### ISSUE THREAD

**Issue by Mijotchi** [Mijotchi/aapt-10.0-release#1]
When the JNI is compiled, it gives more than 10mb, I just wanted to compile only aapt, if I take other types, it gives an error and I have to compile it together with AAPT, is there a way to reduce the size for traditional size of aapt?

**Comment by Mijotchi** [comment]
@TimScriptov Can you help me?

**Comment by MrIkso** [comment]
it is necessary that other libraries also gathered in so, then libaapt.so will weigh somewhere 400-500 kb

**Comment by Mijotchi** [comment]
Ah, okay, thx :)
I'll try some methods
